/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './poll-create.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './polls.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/forms/src/directives/ng_form';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/validators';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/validators';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/control_container';
var renderType_PollCreateComponent_Host:import0.RenderComponentType = (null as any);
class _View_PollCreateComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PollCreateComponent_0_4:import3.PollCreateComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PollCreateComponent_Host0,renderType_PollCreateComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-poll-create',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PollCreateComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PollCreateComponent_0_4 = new import3.PollCreateComponent(this.parentInjector.get(import8.PollsService));
    this._appEl_0.initComponent(this._PollCreateComponent_0_4,[],compView_0);
    compView_0.create(this._PollCreateComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PollCreateComponent) && (0 === requestNodeIndex))) { return this._PollCreateComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PollCreateComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PollCreateComponent_Host === (null as any))) { (renderType_PollCreateComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_PollCreateComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PollCreateComponentNgFactory:import10.ComponentFactory<import3.PollCreateComponent> = new import10.ComponentFactory<import3.PollCreateComponent>('app-poll-create',viewFactory_PollCreateComponent_Host0,import3.PollCreateComponent);
const styles_PollCreateComponent:any[] = [];
var renderType_PollCreateComponent:import0.RenderComponentType = (null as any);
class _View_PollCreateComponent0 extends import1.AppView<import3.PollCreateComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _NgForm_11_3:import11.NgForm;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import12.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import13.DefaultValueAccessor;
  _RequiredValidator_18_4:import14.RequiredValidator;
  _NG_VALIDATORS_18_5:any[];
  _NG_VALUE_ACCESSOR_18_6:any[];
  _NgModel_18_7:import15.NgModel;
  _NgControl_18_8:any;
  _NgControlStatus_18_9:import12.NgControlStatus;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import13.DefaultValueAccessor;
  _RequiredValidator_26_4:import14.RequiredValidator;
  _NG_VALIDATORS_26_5:any[];
  _NG_VALUE_ACCESSOR_26_6:any[];
  _NgModel_26_7:import15.NgModel;
  _NgControl_26_8:any;
  _NgControlStatus_26_9:import12.NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PollCreateComponent0,renderType_PollCreateComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','panel panel-default');
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','panel-heading');
    this._el_4 = this.renderer.createElement(this._el_3,'h2',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'New Poll',(null as any));
    this._text_6 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','panel-body');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-md-8 col-md-offset-2');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'form',(null as any));
    this._NgForm_11_3 = new import11.NgForm((null as any),(null as any));
    this._ControlContainer_11_4 = this._NgForm_11_3;
    this._NgControlStatusGroup_11_5 = new import12.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-group');
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'for','title');
    this._text_16 = this.renderer.createText(this._el_15,'Title',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-control');
    this.renderer.setElementAttribute(this._el_18,'id','title');
    this.renderer.setElementAttribute(this._el_18,'name','title');
    this.renderer.setElementAttribute(this._el_18,'required','');
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._DefaultValueAccessor_18_3 = new import13.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_18));
    this._RequiredValidator_18_4 = new import14.RequiredValidator();
    this._NG_VALIDATORS_18_5 = [this._RequiredValidator_18_4];
    this._NG_VALUE_ACCESSOR_18_6 = [this._DefaultValueAccessor_18_3];
    this._NgModel_18_7 = new import15.NgModel(this._ControlContainer_11_4,this._NG_VALIDATORS_18_5,(null as any),this._NG_VALUE_ACCESSOR_18_6);
    this._NgControl_18_8 = this._NgModel_18_7;
    this._NgControlStatus_18_9 = new import12.NgControlStatus(this._NgControl_18_8);
    this._text_19 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this.renderer.setElementAttribute(this._el_23,'for','title');
    this._text_24 = this.renderer.createText(this._el_23,'Choices',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-control');
    this.renderer.setElementAttribute(this._el_26,'id','choices');
    this.renderer.setElementAttribute(this._el_26,'name','choices');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Enter a choise per row. Up to 5.');
    this.renderer.setElementAttribute(this._el_26,'required','');
    this.renderer.setElementAttribute(this._el_26,'rows','5');
    this._DefaultValueAccessor_26_3 = new import13.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_26));
    this._RequiredValidator_26_4 = new import14.RequiredValidator();
    this._NG_VALIDATORS_26_5 = [this._RequiredValidator_26_4];
    this._NG_VALUE_ACCESSOR_26_6 = [this._DefaultValueAccessor_26_3];
    this._NgModel_26_7 = new import15.NgModel(this._ControlContainer_11_4,this._NG_VALIDATORS_26_5,(null as any),this._NG_VALUE_ACCESSOR_26_6);
    this._NgControl_26_8 = this._NgModel_26_7;
    this._NgControlStatus_26_9 = new import12.NgControlStatus(this._NgControl_26_8);
    this._text_27 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','btn btn-primry');
    this.renderer.setElementAttribute(this._el_29,'type','submit');
    this._text_30 = this.renderer.createText(this._el_29,'Save',(null as any));
    this._text_31 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    const subscription_0:any = this._NgForm_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_18,'input',this.eventHandler(this._handle_input_18_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_18,'blur',this.eventHandler(this._handle_blur_18_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_26,'input',this.eventHandler(this._handle_input_26_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_26,'blur',this.eventHandler(this._handle_blur_26_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3; }
    if (((token === import14.RequiredValidator) && (18 === requestNodeIndex))) { return this._RequiredValidator_18_4; }
    if (((token === import17.NG_VALIDATORS) && (18 === requestNodeIndex))) { return this._NG_VALIDATORS_18_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_6; }
    if (((token === import15.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_7; }
    if (((token === import19.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_8; }
    if (((token === import12.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_9; }
    if (((token === import13.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3; }
    if (((token === import14.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4; }
    if (((token === import17.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_6; }
    if (((token === import15.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_7; }
    if (((token === import19.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_8; }
    if (((token === import12.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_9; }
    if (((token === import11.NgForm) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgForm_11_3; }
    if (((token === import20.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ControlContainer_11_4; }
    if (((token === import12.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatusGroup_11_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RequiredValidator_18_4.required = currVal_11;
      this._expr_11 = currVal_11;
    }
    changes = (null as any);
    const currVal_13:any = 'title';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_18_7.name = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this.context.title;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_18_7.model = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgModel_18_7.ngOnChanges(changes); }
    const currVal_23:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RequiredValidator_26_4.required = currVal_23;
      this._expr_23 = currVal_23;
    }
    changes = (null as any);
    const currVal_25:any = 'choices';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_26_7.name = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this.context.choises;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_26_7.model = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    if ((changes !== (null as any))) { this._NgModel_26_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = (this._RequiredValidator_18_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_18,'required',((currVal_12 == (null as any))? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_15:any = this._NgControlStatus_18_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_18_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_18_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_18_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_18_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_18_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_24:any = (this._RequiredValidator_26_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_26_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_26_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_26_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_26_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_18_7.ngOnDestroy();
    this._NgModel_26_7.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_11_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_26_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PollCreateComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PollCreateComponent> {
  if ((renderType_PollCreateComponent === (null as any))) { (renderType_PollCreateComponent = viewUtils.createRenderComponentType('/home/ubuntu/workspace/fcc-app-voting/assets/app/polls/poll-create.component.html',0,import9.ViewEncapsulation.None,styles_PollCreateComponent,{})); }
  return new _View_PollCreateComponent0(viewUtils,parentInjector,declarationEl);
}