/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './app.component.css.shim';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/directives/router_link_active';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/router/src/directives/router_outlet';
import * as import18 from './errors/error.component';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/router/src/router_outlet_map';
import * as import24 from '@angular/core/src/linker/component_factory_resolver';
import * as import25 from './errors/error.component.ngfactory';
import * as import26 from './errors/error.service';
import * as import27 from '@angular/core/src/security';
var renderType_AppComponent_Host:import0.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AppComponent_0_4:import3.AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import3.AppComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AppComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import11.ComponentFactory<import3.AppComponent> = new import11.ComponentFactory<import3.AppComponent>('my-app',viewFactory_AppComponent_Host0,import3.AppComponent);
const styles_AppComponent:any[] = [import12.styles];
var renderType_AppComponent:import0.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import3.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import13.RouterLinkWithHref;
  _RouterLinkActive_30_4:import14.RouterLinkActive;
  _query_RouterLink_30_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_30_1:import15.QueryList<any>;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import16.NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import16.NgIf;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import16.NgIf;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import16.NgIf;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _TemplateRef_41_5:any;
  _NgIf_41_6:import16.NgIf;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _RouterOutlet_47_5:import17.RouterOutlet;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  /*private*/ _appEl_72:import2.AppElement;
  _ErrorComponent_72_4:import18.ErrorComponent;
  _text_73:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar navbar-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container-fluid');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_7,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_7,'data-target','#bs-example-navbar-collapse-1');
    this.renderer.setElementAttribute(this._el_7,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','sr-only');
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-bar');
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','icon-bar');
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','icon-bar');
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_19,'href','#');
    this._text_20 = this.renderer.createText(this._el_19,'Poll Voting App',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','collapse navbar-collapse');
    this.renderer.setElementAttribute(this._el_24,'id','bs-example-navbar-collapse-1');
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_26 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','nav navbar-nav navbar-right');
    this._text_28 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'li',(null as any));
    this._el_30 = this.renderer.createElement(this._el_29,'a',(null as any));
    this.renderer.setElementAttribute(this._el_30,'routerLink','/polls');
    this.renderer.setElementAttribute(this._el_30,'routerLinkActive','active-link');
    this._RouterLinkWithHref_30_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_30_4 = new import14.RouterLinkActive(this.parentInjector.get(import9.Router),new import21.ElementRef(this._el_30),this.renderer);
    this._query_RouterLink_30_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_30_1 = new import15.QueryList<any>();
    this._text_31 = this.renderer.createText(this._el_30,'Home',(null as any));
    this._text_32 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_33 = new import2.AppElement(33,27,this,this._anchor_33);
    this._TemplateRef_33_5 = new import22.TemplateRef_(this._appEl_33,viewFactory_AppComponent1);
    this._NgIf_33_6 = new import16.NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_35 = new import2.AppElement(35,27,this,this._anchor_35);
    this._TemplateRef_35_5 = new import22.TemplateRef_(this._appEl_35,viewFactory_AppComponent2);
    this._NgIf_35_6 = new import16.NgIf(this._appEl_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_37 = new import2.AppElement(37,27,this,this._anchor_37);
    this._TemplateRef_37_5 = new import22.TemplateRef_(this._appEl_37,viewFactory_AppComponent3);
    this._NgIf_37_6 = new import16.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_39 = new import2.AppElement(39,27,this,this._anchor_39);
    this._TemplateRef_39_5 = new import22.TemplateRef_(this._appEl_39,viewFactory_AppComponent4);
    this._NgIf_39_6 = new import16.NgIf(this._appEl_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_41 = new import2.AppElement(41,27,this,this._anchor_41);
    this._TemplateRef_41_5 = new import22.TemplateRef_(this._appEl_41,viewFactory_AppComponent5);
    this._NgIf_41_6 = new import16.NgIf(this._appEl_41.vcRef,this._TemplateRef_41_5);
    this._text_42 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_47 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_47 = new import2.AppElement(47,(null as any),this,this._el_47);
    this._RouterOutlet_47_5 = new import17.RouterOutlet(this.parentInjector.get(import23.RouterOutletMap),this._appEl_47.vcRef,this.parentInjector.get(import24.ComponentFactoryResolver),(null as any));
    this._text_48 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_49 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_50 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_51 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','well');
    this._text_52 = this.renderer.createText(this._el_51,'\n  ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'p',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'This applicaition was built by ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'a',(null as any));
    this.renderer.setElementAttribute(this._el_55,'href','https://twitter.com/Hassan_Reyes');
    this.renderer.setElementAttribute(this._el_55,'target','_blank');
    this._text_56 = this.renderer.createText(this._el_55,'@Hassan_Reyes',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,' as part of a FreeCodeCamp challenge.',(null as any));
    this._text_58 = this.renderer.createText(this._el_51,'\n  ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_51,'p',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'The Voting application is build over the MEAN stack, and the repository is: ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'a',(null as any));
    this.renderer.setElementAttribute(this._el_61,'href','https://github.com/hassanreyes/camper-app-voting');
    this.renderer.setElementAttribute(this._el_61,'target','_blank');
    this._text_62 = this.renderer.createText(this._el_61,'On Github',(null as any));
    this._text_63 = this.renderer.createText(this._el_59,'.',(null as any));
    this._text_64 = this.renderer.createText(this._el_51,'\n  ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_51,'p',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'For more information about this app, visit: ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_65,'a',(null as any));
    this.renderer.setElementAttribute(this._el_67,'href','https://www.freecodecamp.com/challenges/build-a-voting-app');
    this.renderer.setElementAttribute(this._el_67,'target','_blank');
    this._text_68 = this.renderer.createText(this._el_67,'FreeCodeCamp-Build a Voting App',(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'.',(null as any));
    this._text_70 = this.renderer.createText(this._el_51,'\n',(null as any));
    this._text_71 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_72 = this.renderer.createElement(parentRenderNode,'app-error',(null as any));
    this._appEl_72 = new import2.AppElement(72,(null as any),this,this._el_72);
    var compView_72:any = import25.viewFactory_ErrorComponent0(this.viewUtils,this.injector(72),this._appEl_72);
    this._ErrorComponent_72_4 = new import18.ErrorComponent(this.parentInjector.get(import26.ErrorService));
    this._appEl_72.initComponent(this._ErrorComponent_72_4,[],compView_72);
    compView_72.create(this._ErrorComponent_72_4,[],(null as any));
    this._text_73 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkWithHref_30_3; }
    if (((token === import14.RouterLinkActive) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkActive_30_4; }
    if (((token === import22.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import16.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6; }
    if (((token === import22.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import16.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6; }
    if (((token === import22.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import16.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    if (((token === import22.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import16.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6; }
    if (((token === import22.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import16.NgIf) && (41 === requestNodeIndex))) { return this._NgIf_41_6; }
    if (((token === import17.RouterOutlet) && (47 === requestNodeIndex))) { return this._RouterOutlet_47_5; }
    if (((token === import18.ErrorComponent) && (72 === requestNodeIndex))) { return this._ErrorComponent_72_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/polls';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_30_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_30_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active-link';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_30_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_30_4.ngOnChanges(changes); }
    const currVal_4:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_33_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_35_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_37_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_39_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_41_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_72_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_30_0.dirty) {
        this._query_RouterLink_30_0.reset([]);
        this._RouterLinkActive_30_4.links = this._query_RouterLink_30_0;
        this._query_RouterLink_30_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_30_1.dirty) {
        this._query_RouterLinkWithHref_30_1.reset([this._RouterLinkWithHref_30_3]);
        this._RouterLinkActive_30_4.linksWithHrefs = this._query_RouterLinkWithHref_30_1;
        this._query_RouterLinkWithHref_30_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_30_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_30_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_30,'href',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_30_3.ngOnDestroy();
    this._RouterLinkActive_30_4.ngOnDestroy();
    this._RouterOutlet_47_5.ngOnDestroy();
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_30_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('/home/ubuntu/workspace/fcc-app-voting/assets/app/app.component.html',0,import10.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _RouterLinkActive_1_4:import14.RouterLinkActive;
  _query_RouterLink_1_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_1_1:import15.QueryList<any>;
  _text_2:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent1,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'routerLink','/mypolls');
    this.renderer.setElementAttribute(this._el_1,'routerLinkActive','active-link');
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_1_4 = new import14.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_1),this.renderer);
    this._query_RouterLink_1_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_1_1 = new import15.QueryList<any>();
    this._text_2 = this.renderer.createText(this._el_1,'My Polls',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/mypolls';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active-link';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_1_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_1_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_1_0.dirty) {
        this._query_RouterLink_1_0.reset([]);
        this._RouterLinkActive_1_4.links = this._query_RouterLink_1_0;
        this._query_RouterLink_1_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_1_1.dirty) {
        this._query_RouterLinkWithHref_1_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_1_4.linksWithHrefs = this._query_RouterLinkWithHref_1_1;
        this._query_RouterLinkWithHref_1_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_1_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_1_4.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AppComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AppComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _RouterLinkActive_1_4:import14.RouterLinkActive;
  _query_RouterLink_1_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_1_1:import15.QueryList<any>;
  _text_2:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent2,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'routerLink','/polls/create');
    this.renderer.setElementAttribute(this._el_1,'routerLinkActive','active-link');
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_1_4 = new import14.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_1),this.renderer);
    this._query_RouterLink_1_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_1_1 = new import15.QueryList<any>();
    this._text_2 = this.renderer.createText(this._el_1,'New Poll',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/polls/create';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active-link';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_1_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_1_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_1_0.dirty) {
        this._query_RouterLink_1_0.reset([]);
        this._RouterLinkActive_1_4.links = this._query_RouterLink_1_0;
        this._query_RouterLink_1_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_1_1.dirty) {
        this._query_RouterLinkWithHref_1_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_1_4.linksWithHrefs = this._query_RouterLinkWithHref_1_1;
        this._query_RouterLinkWithHref_1_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_1_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_1_4.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AppComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AppComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent3 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _RouterLinkActive_1_4:import14.RouterLinkActive;
  _query_RouterLink_1_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_1_1:import15.QueryList<any>;
  _text_2:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent3,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'routerLinkActive','active');
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_1_4 = new import14.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_1),this.renderer);
    this._query_RouterLink_1_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_1_1 = new import15.QueryList<any>();
    this._text_2 = this.renderer.createText(this._el_1,'Signup',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('signup');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_1_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_1_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_1_0.dirty) {
        this._query_RouterLink_1_0.reset([]);
        this._RouterLinkActive_1_4.links = this._query_RouterLink_1_0;
        this._query_RouterLink_1_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_1_1.dirty) {
        this._query_RouterLinkWithHref_1_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_1_4.linksWithHrefs = this._query_RouterLinkWithHref_1_1;
        this._query_RouterLinkWithHref_1_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_1_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_1_4.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AppComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AppComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _RouterLinkActive_1_4:import14.RouterLinkActive;
  _query_RouterLink_1_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_1_1:import15.QueryList<any>;
  _text_2:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent4,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'routerLinkActive','active');
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_1_4 = new import14.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_1),this.renderer);
    this._query_RouterLink_1_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_1_1 = new import15.QueryList<any>();
    this._text_2 = this.renderer.createText(this._el_1,'Signin',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import14.RouterLinkActive) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('signin');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_1_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_1_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_1_0.dirty) {
        this._query_RouterLink_1_0.reset([]);
        this._RouterLinkActive_1_4.links = this._query_RouterLink_1_0;
        this._query_RouterLink_1_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_1_1.dirty) {
        this._query_RouterLinkWithHref_1_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_1_4.linksWithHrefs = this._query_RouterLinkWithHref_1_1;
        this._query_RouterLinkWithHref_1_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_1_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_1_4.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AppComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AppComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent5,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','dropdown');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_2,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_2,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_2,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this.renderer.setElementAttribute(this._el_2,'role','button');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','caret');
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','dropdown-menu');
    this._text_7 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'li',(null as any));
    this._el_9 = this.renderer.createElement(this._el_8,'a',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Sing Out',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.getUserName(),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AppComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AppComponent5(viewUtils,parentInjector,declarationEl);
}